### ISSUE TITLE
How do you pass options to tinyMCE?

### ISSUE THREAD

**Issue by cdolek** [oohaysmlm/autoform-tinymce#1]
The repo doesn't have all files in it so I could not tell :)

Thanks

**Comment by sjkdev21** [comment]
Can you be more specific - what is it you are looking for that is not there?

**Comment by cdolek** [comment]
I would like to be able to provide the init options object for tinymce. 
For example:

```
{
toolbar: false,
menubar: false,
nowrap:true
}
```

**Comment by sjkdev21** [comment]
I wasn't sure how to do this when I originally wrote the package, and as far as I knew nobody was using the package so I never went back and updated it.  Before I fixed it, I ended up finding the "mpowaga:autoform-summernote" package which had all the functionality (and more) of what I was looking for from TinyMCE.  If you would still rather user TinyMCE rather than Summernote, let me know and I will update the package today to take the settings object in via your SimpleSchema definition.

**Comment by cdolek** [comment]
Oh ok I see. 

I did not know about summernote, let me look at that, too. Thanks.

Why did you remove the files? I may send you a pull request if I build it.

**Comment by sjkdev21** [comment]
Thanks man, merged in your PR!

**Comment by cdolek** [comment]
Thank you for the thought in the first place.

Please update the atmospherejs repo too, it might be useful for others!

Cheers

**Comment by sjkdev21** [comment]
Done, thanks.
